// <auto-generated />
using Employees.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employees.Migrations
{
    [DbContext(typeof(EmployeeDataContext))]
    [Migration("20230207193803_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Employees.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://robohash.org/autautea.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "nmorgue0@disqus.com",
                            FirstName = "Nonie",
                            LastName = "Morgue"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://robohash.org/saepeadipiscifugit.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "klowe1@nymag.com",
                            FirstName = "Krishna",
                            LastName = "Lowe"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "https://robohash.org/atquerepudiandaecorporis.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "owilliamson2@washingtonpost.com",
                            FirstName = "Orville",
                            LastName = "Williamson"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "https://robohash.org/liberotemporibusalias.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "ditzkovici3@phpbb.com",
                            FirstName = "Dwayne",
                            LastName = "Itzkovici"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "https://robohash.org/enimsapienteillum.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "sjerisch4@craigslist.org",
                            FirstName = "Shelbi",
                            LastName = "Jerisch"
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "https://robohash.org/omnisillumnostrum.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "jwitcherley5@1und1.de",
                            FirstName = "Jerrilee",
                            LastName = "Witcherley"
                        },
                        new
                        {
                            Id = 7,
                            Avatar = "https://robohash.org/adipiscisequidolor.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "ckobpac6@goo.ne.jp",
                            FirstName = "Caritta",
                            LastName = "Kobpac"
                        },
                        new
                        {
                            Id = 8,
                            Avatar = "https://robohash.org/aliquamquassunt.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "qmccague7@facebook.com",
                            FirstName = "Quincey",
                            LastName = "McCague"
                        },
                        new
                        {
                            Id = 9,
                            Avatar = "https://robohash.org/eaquiserror.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "acundey8@yahoo.com",
                            FirstName = "Aharon",
                            LastName = "Cundey"
                        },
                        new
                        {
                            Id = 10,
                            Avatar = "https://robohash.org/dolorconsecteturdeleniti.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "nanthill9@posterous.com",
                            FirstName = "Neila",
                            LastName = "Anthill"
                        },
                        new
                        {
                            Id = 11,
                            Avatar = "https://robohash.org/veroculpadolore.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "cbroadera@theglobeandmail.com",
                            FirstName = "Cinnamon",
                            LastName = "Broader"
                        },
                        new
                        {
                            Id = 12,
                            Avatar = "https://robohash.org/autveritatisquibusdam.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "gtampinb@example.com",
                            FirstName = "Godfrey",
                            LastName = "Tampin"
                        },
                        new
                        {
                            Id = 13,
                            Avatar = "https://robohash.org/utvoluptasdolorum.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "oandrellic@t-online.de",
                            FirstName = "Olimpia",
                            LastName = "Andrelli"
                        },
                        new
                        {
                            Id = 14,
                            Avatar = "https://robohash.org/odioinqui.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "gebblesd@fema.gov",
                            FirstName = "Grissel",
                            LastName = "Ebbles"
                        },
                        new
                        {
                            Id = 15,
                            Avatar = "https://robohash.org/saepedelenitivoluptas.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "bsutherleye@bing.com",
                            FirstName = "Beckie",
                            LastName = "Sutherley"
                        },
                        new
                        {
                            Id = 16,
                            Avatar = "https://robohash.org/aspernaturautdicta.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "dschohierf@dion.ne.jp",
                            FirstName = "Drusie",
                            LastName = "Schohier"
                        },
                        new
                        {
                            Id = 17,
                            Avatar = "https://robohash.org/dolornobisratione.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "aheisterg@soup.io",
                            FirstName = "Aida",
                            LastName = "Heister"
                        },
                        new
                        {
                            Id = 18,
                            Avatar = "https://robohash.org/estnihilsuscipit.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "vleakeh@umn.edu",
                            FirstName = "Valentia",
                            LastName = "Leake"
                        },
                        new
                        {
                            Id = 19,
                            Avatar = "https://robohash.org/abperspiciatismagnam.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "ogellatelyi@spotify.com",
                            FirstName = "Octavius",
                            LastName = "Gellately"
                        },
                        new
                        {
                            Id = 20,
                            Avatar = "https://robohash.org/blanditiisvoluptasrerum.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "emandyj@webs.com",
                            FirstName = "Erwin",
                            LastName = "Mandy"
                        },
                        new
                        {
                            Id = 21,
                            Avatar = "https://robohash.org/auteavel.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "adevenportk@google.fr",
                            FirstName = "Armand",
                            LastName = "Devenport"
                        },
                        new
                        {
                            Id = 22,
                            Avatar = "https://robohash.org/consequuntureveniethic.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "btorell@mit.edu",
                            FirstName = "Bartel",
                            LastName = "Torel"
                        },
                        new
                        {
                            Id = 23,
                            Avatar = "https://robohash.org/fugitmagnamhic.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "aludgatem@ning.com",
                            FirstName = "Auberta",
                            LastName = "Ludgate"
                        },
                        new
                        {
                            Id = 24,
                            Avatar = "https://robohash.org/voluptatumetet.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "csendalln@bizjournals.com",
                            FirstName = "Claudian",
                            LastName = "Sendall"
                        },
                        new
                        {
                            Id = 25,
                            Avatar = "https://robohash.org/cupiditateestsoluta.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "sdarrello@auda.org.au",
                            FirstName = "Saw",
                            LastName = "Darrell"
                        },
                        new
                        {
                            Id = 26,
                            Avatar = "https://robohash.org/quosconsequaturqui.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "anarracottp@dedecms.com",
                            FirstName = "Arv",
                            LastName = "Narracott"
                        },
                        new
                        {
                            Id = 27,
                            Avatar = "https://robohash.org/temporibusperspiciatiscommodi.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "scloustonq@ow.ly",
                            FirstName = "Silvia",
                            LastName = "Clouston"
                        },
                        new
                        {
                            Id = 28,
                            Avatar = "https://robohash.org/eoseosdoloremque.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "fartistr@fda.gov",
                            FirstName = "Fabio",
                            LastName = "Artist"
                        },
                        new
                        {
                            Id = 29,
                            Avatar = "https://robohash.org/nihiloptiout.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "elents@wikimedia.org",
                            FirstName = "Eldredge",
                            LastName = "Lent"
                        },
                        new
                        {
                            Id = 30,
                            Avatar = "https://robohash.org/solutaarchitectovoluptate.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "agoodlettt@yellowbook.com",
                            FirstName = "Arlin",
                            LastName = "Goodlett"
                        },
                        new
                        {
                            Id = 31,
                            Avatar = "https://robohash.org/teneturquidemexercitationem.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "fkeyseu@mac.com",
                            FirstName = "Fenelia",
                            LastName = "Keyse"
                        },
                        new
                        {
                            Id = 32,
                            Avatar = "https://robohash.org/eligenditotamdelectus.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "mshawlv@is.gd",
                            FirstName = "Merilyn",
                            LastName = "Shawl"
                        },
                        new
                        {
                            Id = 33,
                            Avatar = "https://robohash.org/dolorevoluptatibusaut.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "mwadelinw@bravesites.com",
                            FirstName = "Maryellen",
                            LastName = "Wadelin"
                        },
                        new
                        {
                            Id = 34,
                            Avatar = "https://robohash.org/delenitiomnisperferendis.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "bvanyukovx@vinaora.com",
                            FirstName = "Blondie",
                            LastName = "Vanyukov"
                        },
                        new
                        {
                            Id = 35,
                            Avatar = "https://robohash.org/nostrumharumeveniet.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "lliccardoy@unicef.org",
                            FirstName = "Leon",
                            LastName = "Liccardo"
                        },
                        new
                        {
                            Id = 36,
                            Avatar = "https://robohash.org/corporisquibusdamnisi.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "tburneyz@mac.com",
                            FirstName = "Theodosia",
                            LastName = "Burney"
                        },
                        new
                        {
                            Id = 37,
                            Avatar = "https://robohash.org/laudantiumillorepellendus.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "tbenedyktowicz10@indiatimes.com",
                            FirstName = "Tiffany",
                            LastName = "Benedyktowicz"
                        },
                        new
                        {
                            Id = 38,
                            Avatar = "https://robohash.org/similiquerepellatitaque.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "swathey11@fc2.com",
                            FirstName = "Salomon",
                            LastName = "Wathey"
                        },
                        new
                        {
                            Id = 39,
                            Avatar = "https://robohash.org/utmaximeet.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "fmeineking12@cbsnews.com",
                            FirstName = "Fidelio",
                            LastName = "Meineking"
                        },
                        new
                        {
                            Id = 40,
                            Avatar = "https://robohash.org/doloresomnisaut.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "fdemicoli13@earthlink.net",
                            FirstName = "Ford",
                            LastName = "De Micoli"
                        },
                        new
                        {
                            Id = 41,
                            Avatar = "https://robohash.org/nostrumdoloremqueillum.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "bstebbings14@bbc.co.uk",
                            FirstName = "Bridie",
                            LastName = "Stebbings"
                        },
                        new
                        {
                            Id = 42,
                            Avatar = "https://robohash.org/porroenimdolorem.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "tkarpets15@cmu.edu",
                            FirstName = "Theressa",
                            LastName = "Karpets"
                        },
                        new
                        {
                            Id = 43,
                            Avatar = "https://robohash.org/earumquiaest.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "tleivesley16@prlog.org",
                            FirstName = "Twyla",
                            LastName = "Leivesley"
                        },
                        new
                        {
                            Id = 44,
                            Avatar = "https://robohash.org/voluptatevoluptatemexcepturi.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "acroney17@purevolume.com",
                            FirstName = "Alane",
                            LastName = "Croney"
                        },
                        new
                        {
                            Id = 45,
                            Avatar = "https://robohash.org/possimusvoluptatesquas.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "aurrey18@seesaa.net",
                            FirstName = "Althea",
                            LastName = "Urrey"
                        },
                        new
                        {
                            Id = 46,
                            Avatar = "https://robohash.org/magnamaliasveritatis.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "dphifer19@yale.edu",
                            FirstName = "Desiri",
                            LastName = "Phifer"
                        },
                        new
                        {
                            Id = 47,
                            Avatar = "https://robohash.org/idquaesint.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "cmeecher1a@walmart.com",
                            FirstName = "Cicily",
                            LastName = "Meecher"
                        },
                        new
                        {
                            Id = 48,
                            Avatar = "https://robohash.org/magnipariaturdolor.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "hupstone1b@bloglines.com",
                            FirstName = "Harriott",
                            LastName = "Upstone"
                        },
                        new
                        {
                            Id = 49,
                            Avatar = "https://robohash.org/quaevelitoccaecati.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "cesler1c@reddit.com",
                            FirstName = "Cloe",
                            LastName = "Esler"
                        },
                        new
                        {
                            Id = 50,
                            Avatar = "https://robohash.org/cumqueipsamiste.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "mforsdike1d@skyrock.com",
                            FirstName = "Matelda",
                            LastName = "Forsdike"
                        },
                        new
                        {
                            Id = 51,
                            Avatar = "https://robohash.org/similiqueatqueeos.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "dtrigwell1e@canalblog.com",
                            FirstName = "Deirdre",
                            LastName = "Trigwell"
                        },
                        new
                        {
                            Id = 52,
                            Avatar = "https://robohash.org/impeditnesciuntomnis.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "edemendoza1f@latimes.com",
                            FirstName = "Edgar",
                            LastName = "de Mendoza"
                        },
                        new
                        {
                            Id = 53,
                            Avatar = "https://robohash.org/quodeaunde.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "nmcnicol1g@i2i.jp",
                            FirstName = "Neely",
                            LastName = "McNicol"
                        },
                        new
                        {
                            Id = 54,
                            Avatar = "https://robohash.org/cumcorruptimollitia.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "hfinding1h@dell.com",
                            FirstName = "Henrik",
                            LastName = "Finding"
                        },
                        new
                        {
                            Id = 55,
                            Avatar = "https://robohash.org/voluptatumoptiominima.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "nbrodest1i@surveymonkey.com",
                            FirstName = "Nevil",
                            LastName = "Brodest"
                        },
                        new
                        {
                            Id = 56,
                            Avatar = "https://robohash.org/delectusnumquamnihil.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "bmurr1j@salon.com",
                            FirstName = "Bartholemy",
                            LastName = "Murr"
                        },
                        new
                        {
                            Id = 57,
                            Avatar = "https://robohash.org/aliaseteaque.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "kscragg1k@gov.uk",
                            FirstName = "Kalil",
                            LastName = "Scragg"
                        },
                        new
                        {
                            Id = 58,
                            Avatar = "https://robohash.org/iustoundeperspiciatis.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "acavalier1l@europa.eu",
                            FirstName = "Abigail",
                            LastName = "Cavalier"
                        },
                        new
                        {
                            Id = 59,
                            Avatar = "https://robohash.org/inipsumnihil.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "zlambertciorwyn1m@merriam-webster.com",
                            FirstName = "Zacharie",
                            LastName = "Lambert-Ciorwyn"
                        },
                        new
                        {
                            Id = 60,
                            Avatar = "https://robohash.org/omnisprovidentaperiam.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "wsturges1n@nytimes.com",
                            FirstName = "Wallis",
                            LastName = "Sturges"
                        },
                        new
                        {
                            Id = 61,
                            Avatar = "https://robohash.org/perferendisminimasimilique.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "msleeny1o@blogger.com",
                            FirstName = "Marion",
                            LastName = "Sleeny"
                        },
                        new
                        {
                            Id = 62,
                            Avatar = "https://robohash.org/debitisvoluptasenim.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "brudolph1p@state.gov",
                            FirstName = "Banky",
                            LastName = "Rudolph"
                        },
                        new
                        {
                            Id = 63,
                            Avatar = "https://robohash.org/omnisvoluptatumquidem.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "bkennermann1q@issuu.com",
                            FirstName = "Bernadine",
                            LastName = "Kennermann"
                        },
                        new
                        {
                            Id = 64,
                            Avatar = "https://robohash.org/quisetcupiditate.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "ktattershaw1r@dagondesign.com",
                            FirstName = "Kiri",
                            LastName = "Tattershaw"
                        },
                        new
                        {
                            Id = 65,
                            Avatar = "https://robohash.org/rerumaccusantiumea.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "scollaton1s@cbc.ca",
                            FirstName = "Shanta",
                            LastName = "Collaton"
                        },
                        new
                        {
                            Id = 66,
                            Avatar = "https://robohash.org/sapientedoloremquidem.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "csor1t@angelfire.com",
                            FirstName = "Conrade",
                            LastName = "Sor"
                        },
                        new
                        {
                            Id = 67,
                            Avatar = "https://robohash.org/autevenietpariatur.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "kmankor1u@blinklist.com",
                            FirstName = "Kristo",
                            LastName = "Mankor"
                        },
                        new
                        {
                            Id = 68,
                            Avatar = "https://robohash.org/atquelaborumquidem.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "jeacott1v@digg.com",
                            FirstName = "Janaye",
                            LastName = "Eacott"
                        },
                        new
                        {
                            Id = 69,
                            Avatar = "https://robohash.org/odioutsed.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "mflecknoe1w@csmonitor.com",
                            FirstName = "Myriam",
                            LastName = "Flecknoe"
                        },
                        new
                        {
                            Id = 70,
                            Avatar = "https://robohash.org/nihildoloremab.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "gbumphrey1x@hp.com",
                            FirstName = "Griswold",
                            LastName = "Bumphrey"
                        },
                        new
                        {
                            Id = 71,
                            Avatar = "https://robohash.org/mollitiaipsaeligendi.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "rshovel1y@paypal.com",
                            FirstName = "Rebeka",
                            LastName = "Shovel"
                        },
                        new
                        {
                            Id = 72,
                            Avatar = "https://robohash.org/remquiacorporis.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "sbaulk1z@google.fr",
                            FirstName = "Saidee",
                            LastName = "Baulk"
                        },
                        new
                        {
                            Id = 73,
                            Avatar = "https://robohash.org/nonanimibeatae.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "cbogart20@eventbrite.com",
                            FirstName = "Colene",
                            LastName = "Bogart"
                        },
                        new
                        {
                            Id = 74,
                            Avatar = "https://robohash.org/explicaboquasiinventore.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "vliff21@twitter.com",
                            FirstName = "Vera",
                            LastName = "Liff"
                        },
                        new
                        {
                            Id = 75,
                            Avatar = "https://robohash.org/quosdeseruntsimilique.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "efrantzen22@psu.edu",
                            FirstName = "Euphemia",
                            LastName = "Frantzen"
                        },
                        new
                        {
                            Id = 76,
                            Avatar = "https://robohash.org/velitnamnecessitatibus.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "gfeaveryear23@slashdot.org",
                            FirstName = "Garrard",
                            LastName = "Feaveryear"
                        },
                        new
                        {
                            Id = 77,
                            Avatar = "https://robohash.org/corruptivelitarchitecto.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "hyoxall24@instagram.com",
                            FirstName = "Halsey",
                            LastName = "Yoxall"
                        },
                        new
                        {
                            Id = 78,
                            Avatar = "https://robohash.org/quisveniamunde.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "racott25@twitter.com",
                            FirstName = "Raphael",
                            LastName = "Acott"
                        },
                        new
                        {
                            Id = 79,
                            Avatar = "https://robohash.org/velitestmolestiae.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "djessel26@gravatar.com",
                            FirstName = "Dina",
                            LastName = "Jessel"
                        },
                        new
                        {
                            Id = 80,
                            Avatar = "https://robohash.org/eterrorfugiat.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "kscutter27@livejournal.com",
                            FirstName = "Kerry",
                            LastName = "Scutter"
                        },
                        new
                        {
                            Id = 81,
                            Avatar = "https://robohash.org/ullametrerum.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "gdayce28@cnbc.com",
                            FirstName = "Gianina",
                            LastName = "Dayce"
                        },
                        new
                        {
                            Id = 82,
                            Avatar = "https://robohash.org/doloribuscommodiincidunt.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "ccraisford29@cnn.com",
                            FirstName = "Claudio",
                            LastName = "Craisford"
                        },
                        new
                        {
                            Id = 83,
                            Avatar = "https://robohash.org/doloresmolestiasest.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "ofarren2a@wunderground.com",
                            FirstName = "Otis",
                            LastName = "Farren"
                        },
                        new
                        {
                            Id = 84,
                            Avatar = "https://robohash.org/evenietaliasvelit.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "gbraam2b@shinystat.com",
                            FirstName = "Gertie",
                            LastName = "Braam"
                        },
                        new
                        {
                            Id = 85,
                            Avatar = "https://robohash.org/sedcorruptiad.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "pphette2c@ibm.com",
                            FirstName = "Petr",
                            LastName = "Phette"
                        },
                        new
                        {
                            Id = 86,
                            Avatar = "https://robohash.org/possimusporroconsequatur.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "wthiem2d@prweb.com",
                            FirstName = "Willow",
                            LastName = "Thiem"
                        },
                        new
                        {
                            Id = 87,
                            Avatar = "https://robohash.org/animiinrepellat.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "nhynes2e@gizmodo.com",
                            FirstName = "Nelie",
                            LastName = "Hynes"
                        },
                        new
                        {
                            Id = 88,
                            Avatar = "https://robohash.org/rerumvoluptatemodi.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "jberi2f@wunderground.com",
                            FirstName = "Jasmine",
                            LastName = "Beri"
                        },
                        new
                        {
                            Id = 89,
                            Avatar = "https://robohash.org/inciduntesterror.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "sbonham2g@cbslocal.com",
                            FirstName = "Sibella",
                            LastName = "Bonham"
                        },
                        new
                        {
                            Id = 90,
                            Avatar = "https://robohash.org/sedatquos.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "mpiola2h@nhs.uk",
                            FirstName = "Magda",
                            LastName = "Piola"
                        },
                        new
                        {
                            Id = 91,
                            Avatar = "https://robohash.org/autetquisquam.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "smaudlin2i@cyberchimps.com",
                            FirstName = "Shermie",
                            LastName = "Maudlin"
                        },
                        new
                        {
                            Id = 92,
                            Avatar = "https://robohash.org/consecteturnihilvoluptatem.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "dbarbary2j@i2i.jp",
                            FirstName = "Dulcea",
                            LastName = "Barbary"
                        },
                        new
                        {
                            Id = 93,
                            Avatar = "https://robohash.org/maximedoloreut.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "khabben2k@state.gov",
                            FirstName = "Keefer",
                            LastName = "Habben"
                        },
                        new
                        {
                            Id = 94,
                            Avatar = "https://robohash.org/minusidet.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "dallanby2l@mediafire.com",
                            FirstName = "Dorothy",
                            LastName = "Allanby"
                        },
                        new
                        {
                            Id = 95,
                            Avatar = "https://robohash.org/quiavelpossimus.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "tkippax2m@so-net.ne.jp",
                            FirstName = "Tobias",
                            LastName = "Kippax"
                        },
                        new
                        {
                            Id = 96,
                            Avatar = "https://robohash.org/laudantiumfugacupiditate.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "bgreenlies2n@fotki.com",
                            FirstName = "Burty",
                            LastName = "Greenlies"
                        },
                        new
                        {
                            Id = 97,
                            Avatar = "https://robohash.org/esseitaquemagni.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "hengall2o@google.ru",
                            FirstName = "Harrison",
                            LastName = "Engall"
                        },
                        new
                        {
                            Id = 98,
                            Avatar = "https://robohash.org/sintmolestiaefacere.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "jstimson2p@un.org",
                            FirstName = "Joaquin",
                            LastName = "Stimson"
                        },
                        new
                        {
                            Id = 99,
                            Avatar = "https://robohash.org/explicaboautest.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "rpetyanin2q@shareasale.com",
                            FirstName = "Retha",
                            LastName = "Petyanin"
                        },
                        new
                        {
                            Id = 100,
                            Avatar = "https://robohash.org/saepeconsecteturdoloremque.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "kwakely2r@google.de",
                            FirstName = "Kerstin",
                            LastName = "Wakely"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
